---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.10
  driver_config:
    box: opscode-ubuntu-13.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.10_provisionerless.box

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

- name: debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box


suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[cacert::default]
  attributes:
    cacert:
      certs:
        cacert.org.pem:
          source: 'https://www.cacert.org/certs/root.crt'
          hash:   '99d0fa06'
        cacert.org.class3.pem:
          source: 'http://www.cacert.org/certs/class3.crt'
          hash:   '590d426f'

- name: cacert.org
  run_list:
  - recipe[minitest-handler]
  - recipe[cacert::cacert.org]
