LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  IndentWhenRelativeTo: end

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

EmptyLinesAroundBlockBody:
  Enabled: false
